// frontend/src/app/pages/scores/scores.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { ApiService } from '../../core/api.service';
import { AuthService } from '../../core/auth.service';
import { Course, StudentScore } from '../../core/models';

@Component({
  selector: 'app-scores',
  standalone: true,
  imports: [RouterLink, CommonModule],
  template: `
    <div class="space-y-6 max-w-2xl">
      <h1 class="text-lg font-semibold text-[#1A1A1B]">Мои баллы</h1>
      <div class="bg-white rounded-xl border border-[#E5E7EB] p-4">
        <p class="text-xs font-medium text-[#6B7280] mb-3 uppercase tracking-wide">Выберите курс</p>
        <div class="flex flex-wrap gap-2">
          @if (courseList.length === 0) {
            <div class="text-sm text-[#9CA3AF]">
              Вы не записаны ни на один курс.
              <a routerLink="/courses" class="text-[#005BFF] hover:underline ml-1">Перейти к курсам →</a>
            </div>
          }
          @for (c of courseList; track c.id) {
            <button (click)="selectCourse(c.id)"
              class="px-3 py-1.5 rounded-lg text-sm font-medium border transition-colors"
              [class]="selected() === c.id ? 'bg-[#005BFF] text-white border-[#005BFF]' : 'bg-white text-[#1A1A1B] border-[#E5E7EB] hover:border-[#005BFF]/40'">
              {{ c.code }} — {{ c.title }}
            </button>
          }
        </div>
      </div>

      @if (selected() && !score()) {
        <div class="bg-white rounded-xl border border-[#E5E7EB] p-8 text-center text-sm text-[#9CA3AF]">
          Нет данных по баллам
        </div>
      }

      @if (selected() && score(); as s) {
        <div class="bg-white rounded-xl border border-[#E5E7EB] overflow-hidden">
          <div class="px-5 py-4 border-b border-[#E5E7EB] flex items-center justify-between">
            <span class="text-sm font-semibold text-[#1A1A1B]">{{ s.displayName }}</span>
            <div class="flex items-center gap-3">
              <span class="text-sm text-[#6B7280]">Итог: <span class="font-semibold text-[#1A1A1B]">{{ s.finalScore.toFixed(1) }}</span></span>
              <span class="text-xs font-bold px-2.5 py-1 rounded-full" [class]="markColor(s.mark)">{{ s.mark }}</span>
            </div>
          </div>
          <div class="divide-y divide-[#F3F4F6]">
            @for (n of [1,2,3]; track n) {
              <div class="px-5 py-3.5 flex items-center justify-between">
                <span class="text-sm text-[#6B7280]">Модуль {{ n }}</span>
                <span class="text-sm font-semibold text-[#1A1A1B]">
                  {{ byModule(s, n) !== null ? byModule(s, n)!.toFixed(1) : '—' }}
                </span>
              </div>
            }
          </div>
        </div>
      }
    </div>
  `
})
export class ScoresComponent implements OnInit {
  private api = inject(ApiService);
  private auth = inject(AuthService);

  courseList: Course[] = [];
  selected = signal<string | null>(null);
  score = signal<StudentScore | null>(null);

  ngOnInit() {
    Promise.all([this.api.listCourses(), this.api.myActivities()])
      .then(([courses, acts]) => {
        const codes = new Set(acts.map(a => a.courseCode));
        this.courseList = courses.filter(c => codes.has(c.code));
      })
      .catch(() => this.api.listCourses().then(c => this.courseList = c));
  }

  async selectCourse(id: string) {
    this.selected.set(this.selected() === id ? null : id);
    this.score.set(null);
    if (this.selected()) {
      const userId = this.auth.user()?.id;
      const all = await this.api.courseScores(id).catch(() => [] as StudentScore[]);
      this.score.set(all.find(s => s.studentId === userId) ?? null);
    }
  }

  byModule(s: StudentScore, n: number): number | null {
    return s.modules.find(m => m.moduleNumber === n)?.moduleScore ?? null;
  }

  markColor(mark: string) {
    if (mark.startsWith('5')) return 'text-[#059669] bg-[#D1FAE5]';
    if (mark.startsWith('4')) return 'text-[#005BFF] bg-[#EAF2FF]';
    if (mark.startsWith('3')) return 'text-[#D97706] bg-[#FEF3C7]';
    return 'text-[#DC2626] bg-[#FEE2E2]';
  }
}

// frontend/src/app/(app)/scores/page.tsx
"use client";
import { useEffect, useState } from "react";
import { courses, Course, StudentScore, studentApi } from "@/lib/api";
import { useAuth } from "@/context/AuthContext";
import Link from "next/link";
import { ChevronRight } from "lucide-react";

export default function ScoresPage() {
  const { user } = useAuth();
  const [courseList, setCourseList] = useState<Course[]>([]);
  const [, setEnrolledIds] = useState<Set<string>>(new Set());
  const [selected, setSelected] = useState<string | null>(null);
  const [score, setScore] = useState<StudentScore | null>(null);

  useEffect(() => {
    // Load all courses + enrolled activities to determine which courses I'm in
    Promise.all([
      courses.list(),
      studentApi.myActivities(),
    ]).then(([allCourses, acts]) => {
      // Derive enrolled course codes from activities
      const myCodes = new Set(acts.map(a => a.courseCode));
      const myIds = new Set(allCourses.filter(c => myCodes.has(c.code)).map(c => c.id));
      setEnrolledIds(myIds);
      setCourseList(allCourses.filter(c => myIds.has(c.id)));
    }).catch(() => courses.list().then(setCourseList));
  }, []);

  useEffect(() => {
    if (!selected || !user) return;
    courses.scores(selected)
      .then((all) => setScore(all.find((s) => s.studentId === user.id) ?? null))
      .catch(() => setScore(null));
  }, [selected, user]);

  const byModule = (n: number) => score?.modules.find((m) => m.moduleNumber === n)?.moduleScore ?? null;

  const markColor = (mark: string) => {
    if (mark.startsWith("5")) return "text-[#059669] bg-[#D1FAE5]";
    if (mark.startsWith("4")) return "text-[#005BFF] bg-[#EAF2FF]";
    if (mark.startsWith("3")) return "text-[#D97706] bg-[#FEF3C7]";
    return "text-[#DC2626] bg-[#FEE2E2]";
  };

  return (
    <div className="space-y-6 max-w-2xl">
      <h1 className="text-lg font-semibold text-[#1A1A1B]">Мои баллы</h1>

      <div className="bg-white rounded-xl border border-[#E5E7EB] p-4">
        <p className="text-xs font-medium text-[#6B7280] mb-3 uppercase tracking-wide">Выберите курс</p>
        <div className="flex flex-wrap gap-2">
          {courseList.length === 0 && (
        <div className="text-sm text-[#9CA3AF]">
          Вы не записаны ни на один курс.{" "}
          <Link href="/courses" className="text-[#005BFF] hover:underline inline-flex items-center gap-1">
            Перейти к курсам <ChevronRight size={12} />
          </Link>
        </div>
      )}
          {courseList.map((c) => (
            <button
              key={c.id}
              onClick={() => setSelected(c.id === selected ? null : c.id)}
              className={`px-3 py-1.5 rounded-lg text-sm font-medium border transition-colors ${
                selected === c.id
                  ? "bg-[#005BFF] text-white border-[#005BFF]"
                  : "bg-white text-[#1A1A1B] border-[#E5E7EB] hover:border-[#005BFF]/40"
              }`}
            >
              {c.code} — {c.title}
            </button>
          ))}
        </div>
      </div>

      {selected && !score && (
        <div className="bg-white rounded-xl border border-[#E5E7EB] p-8 text-center text-sm text-[#9CA3AF]">
          Нет данных по баллам
        </div>
      )}

      {selected && score && (
        <div className="bg-white rounded-xl border border-[#E5E7EB] overflow-hidden">
          <div className="px-5 py-4 border-b border-[#E5E7EB] flex items-center justify-between">
            <span className="text-sm font-semibold text-[#1A1A1B]">{score.displayName}</span>
            <div className="flex items-center gap-3">
              <span className="text-sm text-[#6B7280]">
                Итог: <span className="font-semibold text-[#1A1A1B]">{score.finalScore.toFixed(1)}</span>
              </span>
              <span className={`text-xs font-bold px-2.5 py-1 rounded-full ${markColor(score.mark)}`}>
                {score.mark}
              </span>
            </div>
          </div>
          <div className="divide-y divide-[#F3F4F6]">
            {[1, 2, 3].map((n) => {
              const val = byModule(n);
              return (
                <div key={n} className="px-5 py-3.5 flex items-center justify-between">
                  <span className="text-sm text-[#6B7280]">Модуль {n}</span>
                  <span className="text-sm font-semibold text-[#1A1A1B]">
                    {val !== null ? val.toFixed(1) : <span className="text-[#9CA3AF] font-normal">—</span>}
                  </span>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
